package com.binayshaw7777.leaflekt

interface LeaflektControllerInterface {
    fun moveCamera(lat: Double, lng: Double, zoom: Double)
    fun setZoomControlsEnabled(isEnabled: Boolean)
    fun setZoomBounds(minZoom: Double, maxZoom: Double)
    fun setMapStyle(style: LeaflektMapStyle)
    fun setGeoJsonOverlay(overlay: LeaflektGeoJsonOverlay)
    fun executeJavaScript(script: String)
    fun addMarker(info: LeaflektMarkerInfo)
    fun removeMarker(id: String)
    fun updateMarker(info: LeaflektMarkerInfo)
    fun clearMarkers()
    fun addPolyline(info: LeaflektPolylineInfo)
    fun updatePolyline(info: LeaflektPolylineInfo)
    fun removePolyline(id: String)
    fun addPolygon(info: LeaflektPolygonInfo)
    fun updatePolygon(info: LeaflektPolygonInfo)
    fun removePolygon(id: String)
    fun addCircle(info: LeaflektCircleInfo)
    fun updateCircle(info: LeaflektCircleInfo)
    fun removeCircle(id: String)
    fun createClusterGroup(groupId: String, maxClusterRadius: Int = 80)
    fun addMarkersToCluster(groupId: String, markers: List<LeaflektMarkerInfo>)
    fun removeClusterGroup(groupId: String)
}
