package com.binayshaw7777.leaflekt

interface LeaflektControllerInterface {
    fun moveCamera(lat: Double, lng: Double, zoom: Double)
    fun animateCamera(lat: Double, lng: Double, zoom: Double, durationMillis: Int = 1000)
    fun setZoomControlsEnabled(isEnabled: Boolean)
    fun setZoomBounds(minZoom: Double, maxZoom: Double)
    fun setScrollGesturesEnabled(isEnabled: Boolean)
    fun setZoomGesturesEnabled(isEnabled: Boolean)
    fun setMapStyle(style: LeaflektMapStyle)
    fun setGeoJsonOverlay(overlay: LeaflektGeoJsonOverlay)
    fun executeJavaScript(script: String)
    fun fitBounds(sw: LeaflektLatLng, ne: LeaflektLatLng, paddingPx: Int = 0)
    fun addMarker(info: LeaflektMarkerInfo)
    fun addMarkers(markers: List<LeaflektMarkerInfo>)
    fun removeMarker(id: String)
    fun removeMarkers(ids: List<String>)
    fun updateMarker(info: LeaflektMarkerInfo)
    fun clearMarkers()
    fun clearMap()
    fun addPolyline(info: LeaflektPolylineInfo)
    fun updatePolyline(info: LeaflektPolylineInfo)
    fun removePolyline(id: String)
    fun addPolygon(info: LeaflektPolygonInfo)
    fun updatePolygon(info: LeaflektPolygonInfo)
    fun removePolygon(id: String)
    fun addCircle(info: LeaflektCircleInfo)
    fun updateCircle(info: LeaflektCircleInfo)
    fun removeCircle(id: String)
    fun createClusterGroup(groupId: String, maxClusterRadius: Int = 80)
    fun addMarkersToCluster(groupId: String, markers: List<LeaflektMarkerInfo>)
    fun removeClusterGroup(groupId: String)
}
